# Access the id_github file from Secret Manager
steps:
  - id: 'Build image pr'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ls -l
        git submodule init
        git submodule update
        echo $(date +"%Y.%m.%d").$(git rev-list --count main).$(git log --oneline -1 | awk -F/ '{ if ($2=="") print "main"; else print $2;}') > /workspace/IMAGE_VERSION
        cat /workspace/IMAGE_VERSION
options:
  machineType: 'N1_HIGHCPU_8'
