# Access the id_github file from Secret Manager
steps:
  - id: 'Build image pr'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ls -l
        git status
        git submodule init
options:
  machineType: 'N1_HIGHCPU_8'
