steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=secret-name > /root/.ssh/version1key' ]
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # Set up git with key and domain.
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 600 /root/.ssh/version1key
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/version1key
        EOF
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  # Clone the repository.
  - id: 'Pull code from repository'
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone git@github.com:mach-2021/mach-subscriptions.git
        cd mach-subscriptions
        git submodule init
        git submodule update
        echo $(date +"%Y.%m.%d").$(git rev-list --count main).$(git log --oneline -1 | awk -F/ '{ if ($2=="") print "main"; else print $2;}') > /workspace/IMAGE_VERSION
        cat /workspace/IMAGE_VERSION
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - id: 'Build image pr'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ls -l
  - id: 'Build image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -f cloudbuild/Dockerfile -t gcr.io/${PROJECT_ID}/subscriptions:$(cat /workspace/IMAGE_VERSION) .
  - id: 'Push image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push gcr.io/${PROJECT_ID}/subscriptions:$(cat /workspace/IMAGE_VERSION)
  - id: 'Deploy image'
    name: 'gcr.io/${PROJECT_ID}/kustomize'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ${_CLOUDSDK_CONTAINER_CLUSTER} --zone ${_CLOUDSDK_COMPUTE_ZONE} --project ${_PROJECT_ID}
        cd k8s/overlays/${_ENV_NAMESPACE}
        kustomize edit set image gcr.io/project_id_stub/subscriptions=gcr.io/${PROJECT_ID}/subscriptions:$(cat /workspace/IMAGE_VERSION)
        kustomize edit add annotation kubernetes.io/change-cause:"deploying $(cat /workspace/IMAGE_VERSION)"
        kustomize build | kubectl -n ${_ENV_NAMESPACE} apply -f -
        kubectl -n ${_ENV_NAMESPACE} rollout status deployment subscriptions
options:
  machineType: 'N1_HIGHCPU_8'
