apiVersion: v1
kind: Service
metadata:
  name: subscriptions
  labels:
    app: subscriptions
  annotations:
    cloud.google.com/load-balancer-type: Internal
    beta.cloud.google.com/backend-config: '{"ports": {"80":"subscriptions-timeout"}}'
spec:
  selector:
    app: subscriptions
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  type: LoadBalancer
